### ISSUE TITLE
Help for whitelist

### ISSUE THREAD

**Issue by voldin912** [RobotMasterxo/qomswapassets#8]
Today, I sent pull request for my token to list the whitelist.
But it was closed.
Could you explain the reason in detail so that I can do that.
Thank you.

**Comment by RobotMasterxo** [comment]
Updated the criteria :)

**Comment by takanamiharuki0115** [comment]
Thank you for your reply.
I would be appreciated if you reply for these questions.
1. How can I burn LP tokens 100% in QOMSWAP?
2. I understand the criteria like this "We have to create Telegram group and it should be old at least 1 week, and there are 100 holders and 20k liquidity", Is this correct?
3. I created 3 tokens with same name, but I want to delete 2 of them which token address is 0x7591f1f2845fc1ad7a1f231e7d04e964bf67039a and 0x3662e891356f516074d009c4651dc5fe5a73aede.
How to delete these tokens from the DEX?
Best.

**Comment by voldin912** [comment]
I want to know the meaning of 20k.
Is this means 100 holders should have to have at least 20k QOM or 20k USD?
